version: '3.9'
services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123

volumes:
  mongodb_data:
    driver: local
