services:
  api:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123

volumes:
  mongodb_data:
    driver: local
